---
- hosts: all
  become: yes

  tasks:
    - name: Add influx yum repository
      debug:
        msg: This is a test message

    - name: Test copy
      copy:
        src: test.txt
        dst: /home/ec2-user/test.txt
        mode: '0644'
